import subprocess
import sys

#first things first: I need to read in a txt file with phi operator inputs

def create_mf_struct(V, F): #V = groups (assume its an array), F = agg funcs (again assume its an array)
    #interesting that F isnt an array of arrays tho
    code = """
class MFStruct:
    def __init__(self
"""
#params for grouping attributes
    params = []
    for attr in V:
        params.append(f"{attr}=None")
    code += ", ".join(params) + "):\n"

    #then we need 'cols' for each agg func - two for average
    for agg_func in F:
        if "avg" in agg_func:
            code += f"        self.{agg_func}_count = 0\n"
            code += f"        self.{agg_func}_sum = 0\n"
        else:
            code += f"        self.{agg_func} = 0\n"
    return code + "\n"


def main():
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """

    if len(sys.argv) != 2:
        print("No filename was provided")
        sys.exit()
    file = sys.argv[1]
    S, n, V, F, sig, G = 0, 0, 0, 0, 0, 0
    with open(file, 'r') as phi_op:
        S = phi_op.readline().strip()
        n = phi_op.readline().strip()
        V = phi_op.readline().strip()
        F = phi_op.readline().strip()
        sig = phi_op.readline().strip()
        G = phi_op.readline().strip()
    

    body = """
    for row in cur:
        if row['quant'] > 10:
            _global.append(row)
    """

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    main()
